spring:
  application:
    name: config-server
  cloud:
    inetutils:
      # 忽略指定网卡（支持正则），假设你的电脑有 VM 那么该选项是非常有用的一个选项
      ignored-interfaces:             # 忽略 docker0 网卡以及 veth 开头的网卡
      - docker0
      - veth.*
      preferred-networks:             # 使用指定网络地址，选择 eth0 网卡，当然也可以直接写 IP （192.168）
      - eth0
    config:
      server:
        git:
          uri:
          username:
          password:
        default-label: master
# config server 从本地读取配置文件
#        native:
#          search-locations: classpath:/config
#  profiles:
#    active: native
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/