spring:
  application:
    name: config-server
  cloud:
    inetutils:
      # 忽略指定网卡（支持正则），假设你的电脑有 VM 那么该选项是非常有用的一个选项
      ignored-interfaces:             # 忽略 docker0 网卡以及 veth 开头的网卡
      - docker0
      - veth.*
      preferred-networks:             # 使用指定网络地址，选择 eth0 网卡，当然也可以直接写 IP （192.168）
      - eth0
    config:
      server:
        git:
          uri: git@github.com:fulgens-cn/SpringCloudConfig.git
          username: fulgenscn@gmail.com
          # 私有仓库需要密码
          password:
          # 配置远程配置中心仓库在本地的目录，默认会复制一份在本地
          # 文件名如：file:/var/folders/w7/r3rkx7cs175145d2hykf77tr0000gn/T/config-repo-2962355997171944157/product-dev.yml
          # basedir: /Users/fulgens/IdeaProjects/SpringCloudLearning/config-repo
        default-label: master
# config server 从本地读取配置文件
#        native:
#          search-locations: classpath:/config
#  profiles:
#    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"